name: react-ci

on:
  push:
    branches:
      - main , dev
  pull_request:
    branches:
      - main , dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer dependencies
        run: npm ci
        working-directory: pinball_playglass

      - name: Lint
        run: npm run lint
        working-directory: pinball_playglass

      - name: Build React
        run: npm run build
        working-directory: pinball_playglass